FROM eclipse-temurin:21-jdk AS runtime

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk 
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

ENV PORT=8080
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=prod

CMD ["java", "-jar", "app.jar"]
