#=========================
# Project
#=========================
info:
    app:
        name: "@project.name@"
        description: "@project.description@"
        version: "@project.version@"
#=============================================
# Actuator Config
#=============================================
management:
    endpoints:
    # DESABILITA TODOS OS ENDPOINTS DO ACTUADOR
        access:
        default: false
        web:
        # ALTERA O PATH DO ACTUADOR
        base-path: /
        exposure:
            # HABILITA APENAS O ENDPOINT HEALTH
            include: health
    endpoint:
        health:
        # HABILITA O ENDPOINT ?/health?
        access: true
        # Especifica os itens adicionais à serem monitorados pelo readiness
        group:
            liveness:
                include: livenessState, ping
            readiness:
                # * CUIDADO: a escolha de realizar verificações externas deve ser realizada com muito cuidado e pode causar efeitos colaterais
                include: readinessState, ping
        # HABILITA PARA RETORNAR O CAMPO 'DETAILS' AO REQUISITAR /health
        show-details: never
        # HABILITA PROBES - LIVENESS CHECK e READINESS CHECK
        probes:
            enabled: true

    health:
        ping:
            enabled: true
        
        # DESABILITADO PARA NÃO RETORNAR INFORMAÇÕES DO ATRIBUTO 'diskpace' AO REQUISITAR /health
        diskpace:
            enabled: false

        # HABILITA LIVENESS CHECK PARA KUBERNATES
        livenessState:
            enabled: true

        # HABILITA READNESS CHECK PARA KUBERNATES
        readinessState:
            enabled: true
    
    #Rastreabilidade com Micrometer
    tracing:
        sampling:
        probability: 1.0
        propagation: w3c

message:
  exception: 'classpath/message/git'
#=========================
# Swagger
#========================= 
springdoc:
    pathsToMatch: /**
    swagger-ui: 
        enabled: true
        tagSorter: alpha
#=========================
# Server
#========================= 
server:
  port: ${SERVER_PORT:8443}
  shutdown: GRACEFUL        
#=========================
# Postgress
#========================= 
# * Depois configurar as variaveis db_host, db_port e etc em um ambiente de deploy
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASS}

#=========================
# JPA
#=========================
    jpa:
        properties:
            hibernate:
                physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#==============================
# Flyway
#==============================
    flyway:
        enabled: true
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        user: ${DB_USER}
        password: ${DB_PASSWORD}

        locations: classpath:db/migrations
        baseline-on-migrate: true
        validate-on-migrate: true