@ingredientId = ba795d4a-d370-435a-8cc7-d6e0333ad214
POST http://localhost:8081/v1/ingredient HTTP/1.1
Content-Type: {{contentType}}

{
"name": "banana",
"grossWeight": 1000.0,
"netWeight": 800.0,
"rawWeight": 600.0,
"cookedWeight": 500.0
}
###

GET http://localhost:8081/v1/ingredient/{{ingredientId}}/fator-correcao HTTP/1.1
Content-Type: {{contentType}}
Accept: application/json

{
  "id": "{{ingredientId}}",
  "name": "banana",
  "grossWeight": 1000.0,
  "netWeight": 800.0,
  "rawWeight": 600.0,
  "cookedWeight": 500.0
}