name: Backend CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy DEV
        run: echo "Deploy BACKEND HOM (develop)"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy PROD
        run: echo "Deploy BACKEND PROD"