name: Dev Build and Scan

on:
  push:
    branches:
      - develop
      - "feature/**"

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=srv-factor-cc
            -Dsonar.organization=alexan-lima
            -Dsonar.host.url=https://sonarcloud.io

      - name: Snyk Security Scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Verificar incremento de versão no pom.xml
        run: |
          git fetch origin develop
          OLD_VERSION=$(git show origin/develop:pom.xml | grep '<version>' | head -1 | sed 's/[^0-9.]//g')
          NEW_VERSION=$(grep '<version>' pom.xml | head -1 | sed 's/[^0-9.]//g')

          echo "Versão antiga: $OLD_VERSION"
          echo "Versão nova: $NEW_VERSION"

          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "❌ Versão do pom.xml não foi incrementada em relação à develop!"
            exit 1
          else
            echo "✅ Versão incrementada corretamente."
          fi
